### PR TITLE
implement optional 'skiprow' to read_ods.

### PR DESCRIPTION
**Pull request by bessavagner**
As `pandas.read_csv` gives the option to skip reading rows:
- I feel an optional argument to skip rows from file is missing in `read_ods`.
- since rows are parsed through a generator, my solution was to `next(row)` `skiprows` times.
- In attachment a example file: with it, for my analysis purpose, I had to skip 5 rows.
[Dicionário_Microdados_Enem_2021.ods](https://github.com/iuvbio/pandas_ods_reader/files/9846898/Dicionario_Microdados_Enem_2021.ods)

### CODE REVIEW

**Comment by ljnsn** [comment]
Hi, thanks for the PR!

I agree, an option to skip a number of rows would be useful. A few comments before looking at the actual implementation:

- Please use `black` to format the files. You can do so by running `black pandas_ods_reader` from the root of the project. Otherwise, the lint workflow will fail.
- Don't add the `*.ods` to the .gitignore. I assume `.py39` is your virtual environment?
- Please remove the `test.ipynb` and add a test for your changes to tests/test_read_ods that can be run with `pytest`. You'll probably need to add a simple test file as well, check the other examples in test/rsc.

Thanks again, happy to take a closer look once these things are done :)

**Comment by bessavagner** [comment]
Hi, @ljnsn 

Thanks for all observations. I've just adjusted my commit accordingly, and included some other remarks:
- black formater (6 files); ✅
- removed ipynb; added test to skiprow feature; ✅
- changed virtual environment to keep .gitignore clean; ✅
- **changed** `.parsers.fods.get_rows` to a lazy function, since skiprow feature require a generator to be passed as `row` to `.algo.parse_data`. 🆕
- I accidentally deleted 'example_col_lengths.ods', but I made a new one saving 'example_col_lengths.fods' as such. 😅

**Review by ljnsn — CHANGES_REQUESTED** [review]
Sorry, I just got around to reviewing this PR..

First of all, thanks for taking into account the suggested changes.

A few comments:

- Please don't change the poetry.lock file. It should be necessary to change this, since no dependencies were changed by this PR.
- Please remove the example_skiprows.ods file at the top level folder, we don't need it there.
- There is no need to recreate a file when you've accidentally deleted it. This is the beauty of git :) You can restore a file to its state in main (or any other git reference) with `git restore tests/rsc/example_col_lengths.ods --source main`.

Alternatively to the last point, you can also reset your branch to your previous commit with `git reset 6a24fbefc97df0c97041cfa69f17b52fb28dc630`. This leaves your changes in the working directory, but resets the index to your last commit. You can then remove the changes we don't want (poetry.lock, top-level .ods file, change to col_lengths example) and commit the remaining changes. You can then force push to your PR branch using `git push --force`. It's fine to force push to a PR branch in this case, since you're the only one working on it.

If you prefer, I can also make those changes and merge the PR, the changes for the feature itself look fine.

**Review by ljnsn — APPROVED** [review]
Hey, I've just gone ahead and added those changes.

I think this is good to go now, thanks again for you contribution!

**Comment by bessavagner** [comment]
Sorry for I took so long to reply.

>     * Please don't change the poetry.lock file. It should be necessary to change this, since no dependencies were changed by this PR.
> 
>     * Please remove the example_skiprows.ods file at the top level folder, we don't need it there.
>     * There is no need to recreate a file when you've accidentally deleted it. This is the beauty of git :) [...]
> Alternatively to the last point, you can also reset your branch to your previous commit with `git reset 6a24fbefc97df0c97041cfa69f17b52fb28dc630`. This leaves [...]

I'm really new on git, and this is my first contribution ever. Thank you so much for all explanation!

> If you prefer, I can also make those changes and merge the PR, the changes for the feature itself look fine.

And thanks for making those in advance. Happy for contributing!

**Pull request merged**
