### PR TITLE
Fixed dataframe generation when columns have different lengths

### PR DESCRIPTION
**Pull request by fatzh**
Hi,

I needed to load an .ods file into a panda dataframe, and your package failed because some columns where not with the same lengths. I just converted the dict to `pd.Series` in the `load_ods` method to make it work.

Would be nice to merge, it's a small change but behave like the `pd.load_excel` method.

### CODE REVIEW

**Comment by iuvbio** [comment]
Hello,

thanks a lot for your contribution! I had not noticed that issue.. I've added a new test file with differing column lengths and it seems to be loaded without issues. Could you provide an example file that did not work for you?

**Comment by fatzh** [comment]
Here is the error I experienced:

```
In [31]: df = read_ods("/mnt/bird/fatz/test_read_ods.ods", sheet_name)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-31-da157265fcc8> in <module>()
----> 1 df = read_ods("/mnt/bird/fatz/Dropbox/51stfloor/zhdk/20190606_inventar/test_read_ods.ods", sheet_name)

~/.virtualenvs/test/lib/python3.5/site-packages/pandas_ods_reader/parser.py in read_ods(file_or_path, sheet, headers, columns)
     66     """
     67     doc = ezodf.opendoc(file_or_path)
---> 68     df = load_ods(doc, sheet, headers, columns)
     69     return sanitize_df(df)

~/.virtualenvs/test/lib/python3.5/site-packages/pandas_ods_reader/parser.py in load_ods(doc, sheet, headers, columns)
     43                 continue
     44     # and convert to a DataFrame
---> 45     df = pd.DataFrame(df_dict)
     46     return df
     47

~/.virtualenvs/test/lib/python3.5/site-packages/pandas/core/frame.py in __init__(self, data, index, columns, dtype, copy)
    390                                  dtype=dtype, copy=copy)
    391         elif isinstance(data, dict):
--> 392             mgr = init_dict(data, index, columns, dtype=dtype)
    393         elif isinstance(data, ma.MaskedArray):
    394             import numpy.ma.mrecords as mrecords

~/.virtualenvs/test/lib/python3.5/site-packages/pandas/core/internals/construction.py in init_dict(data, index, columns, dtype)
    210         arrays = [data[k] for k in keys]
    211
--> 212     return arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
    213
    214

~/.virtualenvs/test/lib/python3.5/site-packages/pandas/core/internals/construction.py in arrays_to_mgr(arrays, arr_names, index, columns, dtype)
     49     # figure out the index, if necessary
     50     if index is None:
---> 51         index = extract_index(arrays)
     52     else:
     53         index = ensure_index(index)

~/.virtualenvs/test/lib/python3.5/site-packages/pandas/core/internals/construction.py in extract_index(data)
    315             lengths = list(set(raw_lengths))
    316             if len(lengths) > 1:
--> 317                 raise ValueError('arrays must all be same length')
    318
    319             if have_dicts:

ValueError: arrays must all be same length
```

So I assumed it was the length... and in a way it is. But you're right, trying to come to a minimal file to reproduce, I found out it was actually caused by having 2 columns with the same name. The values will get concatenated, resulting in arrays of different lengths. 

The `read_excel` method from the `pandas` package solves this by happening `.1`, `.2` to the column names, which is more elegant... see the different outputs (from my patch, and from `read_excel`):

```
In [10]: df = read_ods("/mnt/bird/fatz/test_read_ods.ods", "HO_Akteur")

In [11]: df
Out[11]:
       ID  name website
0  Acto_1     W   sitea
1  Acto_2     D    None
2  Acto_3     S    None
3    None  None   siteb

In [12]: df2 = pd.read_excel("/mnt/bird/fatz/test_read_ods.xlsx", "HO_Akteur")

In [13]: df2
Out[13]:
       ID name website website.1
0  Acto_1    W   sitea       NaN
1  Acto_2    D     NaN     siteb
2  Acto_3    S     NaN       NaN
```

I got a bit of time this afternoon, I'll look into that. [Here](https://www.dropbox.com/s/cg6qyz5obqter7m/test_read_ods.ods?dl=1) it the minimal file I used to reproduce.

**Comment by fatzh** [comment]
Fixed, I have:

* the duplicated column names are now differentiated by adding `.1`, `.2` etc..
* added a test case with a duplicated column ods file  
* also replaced the `df_dict` by an `OrderedDict` to keep columns in places. It also fixes the test case `test_header_file_with_cols` which was failing:

```
    def test_header_file_with_cols(self):
        path = os.path.join(rsc, header_file)
        columns = ["One", "Two", "Three", "Four", "Five"]
        df = read_ods(path, "Sheet1", columns=columns)
>       assert list(df.columns) == columns
E       AssertionError: assert ['Five', 'Fou...Three', 'Two'] == ['One', 'Two',...Four', 'Five']
E         At index 0 diff: 'Five' != 'One'
E         Use -v to get the full diff
```

Here is the output of the same file (ods and same exported as xlsx) using this package and pandas:

```
In [6]: from pandas_ods_reader import read_ods

In [7]: import pandas as pd

In [8]: df = read_ods("/mnt/bird/fatz/Dropbox/51stfloor/zhdk/20190606_inventar/test_read_ods.ods", "Sheet1")

In [9]: df
Out[9]:
       ID name website website.1
0  Acto_1    W   sitea      None
1  Acto_2    D    None     siteb
2  Acto_3    S    None      None

In [10]: df2 = pd.read_excel("/mnt/bird/fatz/Dropbox/51stfloor/zhdk/20190606_inventar/test_read_ods.xlsx", "Sheet1")

In [11]: df2
Out[11]:
       ID name website website.1
0  Acto_1    W   sitea       NaN
1  Acto_2    D     NaN     siteb
2  Acto_3    S     NaN       NaN
```

Looks good, what do you think ?

**Comment by fatzh** [comment]
great, and rebase done!

**Comment by iuvbio** [comment]
Thanks again for taking the time to provide feedback and improve the package. And congrats on being the first contributor :smiley:

**Comment by fatzh** [comment]
Super, thanks for bumping the version, and thanks for the project ;)

**Pull request merged**
